const theme = {
  mainBlack: '#333333',
  borderBlue: '#258bf7',
  mainBlue: '#36f',
  textGray: '#999999',
  mint: '#00aead',
  bgGray: '#333333',
  bgMint: '#e4f4ec',
  footerTitle: '#3a3a3a',
  footerText: '#767676',
  borderGray: '#e1e2e3',
  tagGray: '#f3f5f8',
  loginBg: '#f7f7f7',
  loginGray: '#888888',
  alertRed: '#fe415c',
  disabledGray: '#f2f4f7',
  modalGray: '#f8f8fa',
  modalText: '#b5b5b5',
  mainFont: 'PretendardVariable',
  fontBlack: 'Pretendard-Black',
  fontReg: 'Pretendard-Regular',
  fontMd: 'Pretendard-Medium',
  fontSb: 'Pretendard-SemiBold',
  fontThin: 'Pretendard-Thin',
};

export default theme;
